name: Linting, Test, Deploy
on: [push, workflow_dispatch]
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Does the linting
              run: npm run lint
            - name: End of linting message
              run: echo "Linting complete"
 
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run tests
              run: npm test