name: Linting, Test, Deploy
# on: [push, workflow_dispatch]
on: workflow_dispatch
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm install
            - name: Does the linting
              run: npm run lint
            - name: End of linting message
              run: echo "Linting complete"
 
    testing:
        needs: linting
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run tests
              run: npm test

    build:
        needs: testing
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v2
            - name: Install nodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Build it
              run: npm run build
            - name: Build Complete echo
              run: echo "Build has been complete"

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Do the deploy
              run: echo "Deploying..."
            - name: Completed echo
              run: echo "Deploy Completed!"